<cf> ::= np.where(<cond>, 0, 1)
<cond> ::= (<var> <relop> <var>) | (<cond> <lop> <cond>)
                                     # Combinazione lineare delle features              # Interazione tra features          # Attivazione non lineare   
<var> ::= x[:, <varidx>] | 0.<d><d> | <coef> * x[:, <varidx>] + <coef> * x[:, <varidx>] | x[:, <varidx1>] * x[:, <varidx2>] | <activation>
                 # ReLU                # Sigmoid                 # Tahn
<activation> ::= np.maximum(0, <var>) | 1 / (1 + np.exp(-<var>)) | np.tanh(<var>)

<lop> ::= & | "|"
<relop> ::= > | < | >= | <=   

<d> ::= GE_RANGE:9
<coef> ::= 0.<d><d> | <d>.<d><d> 
<varidx> ::= GE_RANGE:dataset_n_vars
<varidx1> ::= GE_RANGE:dataset_n_vars
<varidx2> ::= GE_RANGE:dataset_n_vars